# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

def common_pods
  pod 'Alamofire'
  pod 'AlamofireImage', '~> 3.3'
end

target 'world-quizz-base' do
	inhibit_all_warnings!
  	common_pods

target 'world-quizz-baseTests' do
    inhibit_all_warnings!
    inherit! :search_paths
    pod 'KIF'
    pod 'KIF/IdentifierTests'
    pod 'OHHTTPStubs/Swift'

   post_install do |installer|
     installer.pods_project.targets.each do |target|
       target.build_configurations.each do |config|
         config.build_settings['ENABLE_BITCODE'] = 'NO'
       end
     end
   end
 end
end

